### ISSUE TITLE
About trained checkpoint

### ISSUE THREAD

**Issue by yjhong89** [kdmayer/PV_Pipeline#2]
Dear authors of deep solar for germany,

Is there a trained checkpoint for classifying solar panels ?

I saw 'checkpoint_path' in config.yml file, but there isn't any checkpoint file in this directory.

Thank you in advance.

Regards, YJHong.

**Comment by kdmayer** [comment]
Hi YJHong,

Thank you for reaching out!

I will bring up your request in our upcoming research group meeting (November 16th) and get back to you once I had a chance to speak with my professor. 

Best regards,

Kevin

**Comment by kdmayer** [comment]
Hi YJHong,

I have uploaded both model checkpoints to the repository. 

DeepSolar_GoogleMaps_classification.tar should have a precision of 92% and a recall of 98% on aerial imagery provided by Google Maps Static API (zoom level=21, GSD of 5 cm/pixel)

DeepSolar_openNRW_classification.tar should have a precision of 64% and a recall of 87% on aerial imagery provided by the openNRW portal (GSD of 10 cm/pixel)

Best,

Kevin

**Comment by yjhong89** [comment]
@kdmayer 

Thank you a lot! 

YJ Hong.
