### ISSUE TITLE
Reproducible environment with conda-lock

### ISSUE THREAD

**Issue by Baschdl** [kdmayer/PV_Pipeline#3]
I cannot reproduce your environment on a Ubuntu machine using the `requirements.txt`
https://github.com/kdmayer/PV_Pipeline/blob/8ff5c0f14a5182af4a9add05f8b0400c7d0c8617/requirements.txt#L3-L7
as it includes osx-specific build names for the packages. Could you generate a new `environment.yml` using [conda-lock](https://github.com/conda-incubator/conda-lock) instead of `conda-export` as [its use is discouraged for reproducible environments](https://github.com/olegtarasov/conda-export#what-about-exactly-reproducible-environments)?

I tried to just remove the build numbers using https://stackoverflow.com/a/56780297/3342058 but that didn't work. I guess one would need a matching OS, python version and conda version to be able to reproduce it.

**Comment by kdmayer** [comment]
Hi Baschdl,

Sure, I can look into that. In the meantime, I think it is easiest if you install the individual libraries manually. It should only be a handful of libraries that are actually needed to run this repo, i.e. torch, PIL, shapely, etc.

Hope that helps,
Kevin
